// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Db;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123161306_MultipleElectricityCompanies")]
    partial class MultipleElectricityCompanies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("backend.Db.ElectricityCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ElectricityCompanies");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeason", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Season")
                        .IsUnique();

                    b.ToTable("ElectricityCompanySeasons");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDay", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Day")
                        .IsUnique();

                    b.ToTable("ElectricityCompanySeasonDays");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDayEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DayId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayId", "Type")
                        .IsUnique();

                    b.ToTable("ElectricityCompanySeasonDayEntries");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDayEntryRange", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EndHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartHour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("ElectricityCompanySeasonDayEntryRanges");
                });

            modelBuilder.Entity("backend.Db.PeakDataLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("City", "CountryCode")
                        .IsUnique();

                    b.HasIndex("City", "StateCode", "CountryCode");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompany", b =>
                {
                    b.HasOne("backend.Db.PeakDataLocation", "Location")
                        .WithMany("ElectricityCompanies")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeason", b =>
                {
                    b.HasOne("backend.Db.ElectricityCompany", "Company")
                        .WithMany("Seasons")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDay", b =>
                {
                    b.HasOne("backend.Db.ElectricityCompanySeason", "Season")
                        .WithMany("Days")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDayEntry", b =>
                {
                    b.HasOne("backend.Db.ElectricityCompanySeasonDay", "Day")
                        .WithMany("Entries")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDayEntryRange", b =>
                {
                    b.HasOne("backend.Db.ElectricityCompanySeasonDayEntry", "Entry")
                        .WithMany("Ranges")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompany", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeason", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDay", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("backend.Db.ElectricityCompanySeasonDayEntry", b =>
                {
                    b.Navigation("Ranges");
                });

            modelBuilder.Entity("backend.Db.PeakDataLocation", b =>
                {
                    b.Navigation("ElectricityCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
